from typing import Dict, Any, List
from supabase import Client, create_client

def get_supabase_client(url: str, key: str) -> Client:
    return create_client(url, key)

def format_analysis_result(run_id: str, filename: str, payload: Dict[str, Any], analysis_type: str) -> Dict[str, Any]:
    r = payload["results"]
    return {
        "run_id": run_id,
        "filename": filename,
        "analysis_type": analysis_type,
        "roi_image_path": None,
        "mask_image_path": None,
        "day": r.get("day"),
        "organoid_number": r.get("organoidNumber") or r.get("organoid_number"),
        "growth_rate": r.get("growthRate") if r.get("growthRate") is not None else r.get("growth_rate"),
        "area": r.get("area"),
        "perim": r.get("perim"),
        "eqdiam": r.get("eqDiam"),
        "circ": r.get("circ"),
        "ar": r.get("ar"),
        "roundness": r.get("round"),
        "solidity": r.get("solidity"),
        "major": r.get("major"),
        "minor": r.get("minor"),
        "angle": r.get("angle"),
        "feret": r.get("feret"),
        "minferet": r.get("minFeret"),
        "feretangle": r.get("feretAngle"),
        "feretx": r.get("feretX"),
        "ferety": r.get("feretY"),
        "x": r.get("x"),
        "y": r.get("y"),
        "xm": r.get("xm"),
        "ym": r.get("ym"),
        "centroidtocom": r.get("centroidToCom"),
        "bx": r.get("bx"),
        "by": r.get("by"),
        "width": r.get("width"),
        "height": r.get("height"),
        "mean": r.get("mean"),
        "median": r.get("median"),
        "mode": r.get("mode"),
        "min": r.get("min"),
        "max": r.get("max"),
        "stddev": r.get("stdDev"),
        "skew": r.get("skew"),
        "kurt": r.get("kurt"),
        "rawintden": r.get("rawIntDen"),
        "intden": r.get("intDen"),
        "corrtotalint": r.get("corrTotalInt"),
        "corrmeanint": r.get("corrMeanInt"),
        "corrminint": r.get("corrMinInt"),
        "corrmaxint": r.get("corrMaxInt"),
        "bgring": r.get("bgRing"),
        "analyze_s": r.get("analyze_s"),
        "calculation_s": r.get("calculation_s"),
        "decode_rgb_s": r.get("decode_rgb_s"),
        "total_request_s": r.get("total_request_s"),
        "results_json": payload.get("results"),
        "profile_json": payload.get("profile"),
    }
